import React from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowRight,
  Shield,
  CheckCircle,
  Clock,
  Eye,
  Target,
  TrendingUp,
  BarChart3,
  Users,
  Database,
  Activity,
  Heart,
  FileText,
  DollarSign,
  PieChart,
  GitBranch,
  AlertCircle,
  Award,
  Zap,
  Percent,
  Layers,
  Radio,
  Tv,
  Smartphone,
  Newspaper,
} from "lucide-react";
import PageLayout from "../../../components/Layout/PageLayout";
import styles from "./MarketingMixModelingPage.module.css";
import SEO from '../../../components/SEO/SEO';
import { buildServiceSchema } from '../../../utils/serviceSchema';

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

const steps = [
  {
    icon: <Database size={22} />,
    title: "Data Integration & Harmonization",
    desc: "We aggregate data from all your marketing channels — TV, digital, social, print, radio, and events — along with internal sales data and external factors like seasonality and economic indicators. We harmonize these disparate data sources into a unified analytics platform, ensuring consistency and accuracy."
  },
  {
    icon: <BarChart3 size={22} />,
    title: "Model Development & Attribution",
    desc: "We build sophisticated statistical and machine learning models — including regression, time-series, and Bayesian methods — to quantify the impact of each marketing channel on sales and revenue. We attribute incremental revenue to each channel, accounting for interactions and diminishing returns."
  },
  {
    icon: <Radio size={22} />,
    title: "Channel Performance & ROI Analysis",
    desc: "We assess the effectiveness and ROI of each marketing channel and campaign. We identify which channels are driving the most revenue, which are underperforming, and where you're getting the best return on your marketing spend."
  },
  {
    icon: <Target size={22} />,
    title: "Budget Optimization & Allocation",
    desc: "We use optimization algorithms to recommend the optimal allocation of your marketing budget across channels. We maximize revenue and ROI while respecting budget constraints, ensuring every dollar is spent where it has the greatest impact."
  },
  {
    icon: <PieChart size={22} />,
    title: "Scenario Planning & What‑If Analysis",
    desc: "We enable you to simulate different budget allocation scenarios and assess their impact on revenue and ROI. You can test the effect of increasing spend on one channel, decreasing on another, or introducing new channels — before committing real budget."
  },
  {
    icon: <TrendingUp size={22} />,
    title: "Continuous Monitoring & Optimization",
    desc: "We provide real‑time dashboards that track marketing performance, channel ROI, and budget utilization. We continuously refine models as new data emerges, ensuring your marketing strategy remains optimized and responsive to changing conditions."
  },
];

const features = [
  {
    icon: <Tv size={22} />,
    title: "Multi‑Channel Attribution",
    desc: "Accurately attribute revenue to TV, digital, social, print, radio, and events, accounting for interactions and synergy between channels."
  },
  {
    icon: <Percent size={22} />,
    title: "ROI & ROAS Analysis",
    desc: "Measure the return on investment and return on ad spend for each channel and campaign, enabling data‑driven budget allocation."
  },
  {
    icon: <Target size={22} />,
    title: "Budget Optimization & Re‑allocation",
    desc: "Optimize your marketing budget allocation to maximize revenue and ROI, using advanced mathematical optimization algorithms."
  },
  {
    icon: <Activity size={22} />,
    title: "Baseline & Incremental Lift Analysis",
    desc: "Separate the impact of marketing from baseline sales, quantifying the true incremental lift generated by each channel."
  },
  {
    icon: <Eye size={22} />,
    title: "Real‑Time Performance Dashboards",
    desc: "Monitor marketing performance, channel ROI, and budget utilization in real‑time, enabling rapid adjustments and optimization."
  },
  {
    icon: <GitBranch size={22} />,
    title: "Scenario Planning & Forecasting",
    desc: "Simulate the impact of different budget allocation scenarios and forecast future revenue and ROI under various conditions."
  },
];

const benefits = [
  {
    icon: <DollarSign size={18} />,
    title: "20‑40% Marketing ROI Improvement",
    desc: "Optimize budget allocation to channels that drive the highest returns, significantly improving overall marketing ROI."
  },
  {
    icon: <Target size={18} />,
    title: "Data‑Driven Budget Allocation",
    desc: "Replace guesswork with evidence‑based decisions about where to invest your marketing spend."
  },
  {
    icon: <Zap size={18} />,
    title: "Faster, Smarter Decisions",
    desc: "Access real‑time insights that enable rapid adjustments to marketing strategy and budget allocation."
  },
  {
    icon: <Users size={18} />,
    title: "Better Stakeholder Alignment",
    desc: "Provide clear, evidence‑based attribution and ROI metrics that align marketing and finance teams."
  },
  {
    icon: <Shield size={18} />,
    title: "Reduced Wasted Spend",
    desc: "Eliminate spend on underperforming channels and reinvest in high‑ROI activities, reducing waste and improving efficiency."
  },
  {
    icon: <Award size={18} />,
    title: "Competitive Advantage",
    desc: "Outperform competitors with a more effective, data‑driven marketing strategy that delivers superior ROI."
  },
];

const MarketingMixModelingPage = () => {
  return (
    <PageLayout>
    <SEO
      title="Marketing Mix Modeling | Scape Data Solutions"
      description="AI-powered marketing mix modeling that quantifies channel impact and optimizes budget allocation."
      path="/services/marketing-mix-modeling"
      schema={buildServiceSchema({
        name: "Marketing Mix Modeling",
        description: "AI-powered marketing mix modeling that quantifies channel impact and optimizes budget allocation.",
        path: "/services/marketing-mix-modeling",
      })}
    />

      <section className={styles.heroSection}>
        <div className={styles.heroOverlay} />
        <div className={styles.container}>
          <motion.div className={styles.heroContent} initial="hidden" animate="visible" variants={fadeUp}>
            <motion.div className={styles.heroBadge} variants={fadeUp}>
              <PieChart size={14} /> <span>Marketing Mix Modeling (MMM)</span>
            </motion.div>
            <motion.h1 className={styles.heroTitle} variants={fadeUp}>
              Optimize Every <span className={styles.highlight}>Marketing Dollar</span>
            </motion.h1>
            <motion.p className={styles.heroSub} variants={fadeUp}>
              AI-powered marketing mix modeling that quantifies the impact of every marketing channel,
              optimizes budget allocation, and maximizes ROI. Transform your marketing into a
              predictable, high‑performance growth engine.
            </motion.p>
            <motion.div className={styles.heroCta} variants={fadeUp}>
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Link to="/contact" className={styles.heroBtn}>
                  Optimize Your Marketing Spend <ArrowRight size={16} />
                </Link>
              </motion.div>
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <a href="#how-it-works" className={styles.heroBtnSecondary}>
                  See How It Works <Eye size={15} />
                </a>
              </motion.div>
            </motion.div>
            <motion.div className={styles.heroStats} variants={fadeUp}>
              <div className={styles.statItem}>
                <span className={styles.statValue}>20-40%</span>
                <span className={styles.statLabel}>ROI Improvement</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statValue}>30%</span>
                <span className={styles.statLabel}>Waste Reduction</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statValue}>95%</span>
                <span className={styles.statLabel}>Attribution Accuracy</span>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      <section className={styles.problemSection}>
        <div className={styles.container}>
          <motion.div
            className={styles.problemContent}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            <span className={styles.problemLabel}>The Challenge</span>
            <h2>Marketing Spend is <span className={styles.highlight}>Fragmented and Unpredictable</span></h2>
            <div className={styles.problemGrid}>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>50%</span>
                <p>Of marketing budgets are wasted on underperforming channels — but most companies can't identify which ones without robust attribution modeling.</p>
              </div>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>40%</span>
                <p>Of marketers lack the analytics to measure the true ROI of their campaigns, relying on last‑click attribution that overvalues digital and undervalues brand channels.</p>
              </div>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>$200B+</span>
                <p>Estimated annual waste in global marketing spend due to suboptimal allocation and lack of accurate attribution.</p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <section className={styles.overviewSection}>
        <div className={styles.container}>
          <div className={styles.overviewGrid}>
            <motion.div
              className={styles.overviewText}
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: false, amount: 0.2 }}
              transition={{ duration: 0.6 }}
            >
              <h2>
                Quantify. Optimize. <span className={styles.highlight}>Dominate.</span>
              </h2>
              <p>
                Marketing spend is one of the largest investments a company makes — yet it's often
                one of the least understood. Without accurate attribution, you can't know which
                channels are driving revenue, which are wasting money, or how to allocate your
                budget for maximum impact.
              </p>
              <p>
                Our Marketing Mix Modeling (MMM) service uses advanced statistical and machine
                learning techniques to quantify the impact of every marketing channel — TV,
                digital, social, print, radio, events, and more — on your sales and revenue.
              </p>
              <p>
                We attribute incremental revenue to each channel, accounting for interactions,
                synergies, and diminishing returns. We identify which channels are driving the
                highest ROI and recommend optimal budget allocations to maximize revenue and
                profitability.
              </p>
              <p>
                With our solution, you transform marketing from a cost center into a predictable,
                high‑performance growth engine. You allocate every dollar where it has the
                greatest impact, achieving superior ROI and sustainable growth.
              </p>
            </motion.div>
            <motion.div
              className={styles.overviewVisual}
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: false, amount: 0.2 }}
              transition={{ duration: 0.6 }}
            >
              <div className={styles.visualPlaceholder}>
                <PieChart size={48} />
                <span>Marketing Mix Modeling</span>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className={styles.howSection} id="how-it-works">
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            How We Build Your Marketing Mix Model
          </motion.h2>
          <div className={styles.howGrid}>
            {steps.map((step, index) => (
              <motion.div
                key={index}
                className={styles.howCard}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false, amount: 0.15 }}
                variants={cardVariants}
                whileHover={{ y: -4, boxShadow: "0 8px 24px rgba(0,0,0,0.05)" }}
              >
                <div className={styles.howIcon}>{step.icon}</div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.deliverablesSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            What We Deliver
          </motion.h2>
          <div className={styles.deliverablesGrid}>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Comprehensive Marketing Mix Model</h4>
                <p>A robust, validated model that quantifies the impact of each marketing channel on sales and revenue, with clear attribution and ROI metrics.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Channel Performance & ROI Report</h4>
                <p>Detailed analysis of the effectiveness and ROI of each channel, with recommendations for optimization.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Budget Optimization Recommendations</h4>
                <p>Optimal budget allocation across channels to maximize revenue and ROI, with clear rationale and expected impact.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Scenario Planning & What‑If Analysis Tool</h4>
                <p>Interactive tool to simulate the impact of different budget allocation scenarios and forecast revenue and ROI.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Executive & Marketing Dashboards</h4>
                <p>Real‑time dashboards that track marketing performance, channel ROI, and budget utilization, with drill‑down capabilities.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Continuous Model Refinement & Support</h4>
                <p>Ongoing refinement of models as new data emerges, ensuring your marketing strategy remains optimized and responsive.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.featuresSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            Core Capabilities
          </motion.h2>
          <div className={styles.featuresGrid}>
            {features.map((feature, index) => (
              <motion.div
                key={index}
                className={styles.featureCard}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false, amount: 0.15 }}
                variants={cardVariants}
                whileHover={{ y: -4, boxShadow: "0 8px 24px rgba(0,0,0,0.05)" }}
              >
                <div className={styles.featureIcon}>{feature.icon}</div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.benefitsSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            Why Choose Us?
          </motion.h2>
          <div className={styles.benefitsGrid}>
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                className={styles.benefitCard}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: false, amount: 0.15 }}
                transition={{ duration: 0.4, delay: index * 0.06 }}
                whileHover={{ x: 4 }}
              >
                <div className={styles.benefitIcon}>{benefit.icon}</div>
                <div>
                  <h3>{benefit.title}</h3>
                  <p>{benefit.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.ctaSection}>
        <div className={styles.container}>
          <motion.div
            className={styles.ctaContent}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.6 }}
          >
            <h2>Ready to Maximize Your Marketing ROI?</h2>
            <p>
              Let's build a marketing mix model that gives you clarity, confidence, and control over
              your marketing spend. You'll know exactly where every dollar should go to drive
              maximum revenue and growth.
            </p>
            <motion.div whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}>
              <Link to="/contact" className={styles.ctaBtn}>
                Get Started <ArrowRight size={18} />
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>
    </PageLayout>
  );
};

export default MarketingMixModelingPage;
