import React from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowRight,
  Shield,
  CheckCircle,
  Clock,
  Eye,
  Target,
  TrendingUp,
  BarChart3,
  Users,
  Database,
  Activity,
  DollarSign,
  PieChart,
  AlertCircle,
  Award,
  Zap,
  Layers,
  Heart,
  Gift,
  Star,
} from "lucide-react";
import PageLayout from "../../../components/Layout/PageLayout";
import styles from "./CustomerLoyaltyAnalyticsPage.module.css";
import SEO from '../../../components/SEO/SEO';
import { buildServiceSchema } from '../../../utils/serviceSchema';

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut" } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } },
};

const steps = [
  {
    icon: <Database size={22} />,
    title: "Loyalty Data Integration & Enrichment",
    desc: "We consolidate data from your loyalty program, POS, e‑commerce, CRM, and customer feedback systems. We enrich each customer profile with transaction history, engagement metrics, reward redemptions, and behavioral attributes."
  },
  {
    icon: <Star size={22} />,
    title: "Customer Segmentation & Loyalty Tiers",
    desc: "We segment customers by loyalty program tier, purchase frequency, average order value, and engagement. We identify your most valuable advocates, casual customers, and at‑risk members, enabling targeted retention and reward strategies."
  },
  {
    icon: <Heart size={22} />,
    title: "Loyalty Program Performance Analytics",
    desc: "We assess the effectiveness of your loyalty program — redemption rates, incremental spend, member acquisition cost, and program ROI. We pinpoint which rewards drive the highest engagement and which are underutilized."
  },
  {
    icon: <PieChart size={22} />,
    title: "Churn Prediction & Retention Modeling",
    desc: "We build machine learning models to identify customers likely to disengage or churn. We predict the probability of a member becoming inactive and recommend proactive interventions — personalized offers, targeted communications, or tier upgrades."
  },
  {
    icon: <Gift size={22} />,
    title: "Reward Optimization & Personalization",
    desc: "We recommend the most effective rewards for each customer segment — points, exclusive discounts, early access, or personalized gifts. We optimize reward structure to maximize member satisfaction and business profitability."
  },
  {
    icon: <TrendingUp size={22} />,
    title: "Continuous Monitoring & Improvement",
    desc: "We provide real‑time dashboards that track loyalty program KPIs — active members, redemption rates, average spend per member, and program ROI. We continuously refine strategies based on member behavior and program performance."
  },
];

const features = [
  {
    icon: <Users size={22} />,
    title: "Customer Loyalty Dashboard",
    desc: "Real‑time visibility into loyalty program health — member engagement, redemption trends, and financial impact."
  },
  {
    icon: <Heart size={22} />,
    title: "Member Lifetime Value (LTV) Prediction",
    desc: "Predict the future value of each loyalty member based on transaction history, engagement, and program behavior."
  },
  {
    icon: <Target size={22} />,
    title: "Redemption & Reward Analytics",
    desc: "Track reward redemption rates, identify popular rewards, and understand how rewards influence customer behavior."
  },
  {
    icon: <Star size={22} />,
    title: "Segment & Tier Performance",
    desc: "Compare performance across loyalty tiers and segments, identifying opportunities to upgrade or re‑engage members."
  },
  {
    icon: <AlertCircle size={22} />,
    title: "Churn & Inactivity Alerts",
    desc: "Proactive alerts for members showing signs of disengagement, enabling timely intervention to re‑activate them."
  },
  {
    icon: <BarChart3 size={22} />,
    title: "Program ROI & Incrementality",
    desc: "Measure the incremental revenue generated by the loyalty program, separating program‑driven lift from baseline behavior."
  },
];

const benefits = [
  {
    icon: <DollarSign size={18} />,
    title: "Increased Customer Lifetime Value",
    desc: "Build deeper relationships with loyal customers, driving repeat purchases, higher AOV, and long‑term revenue."
  },
  {
    icon: <TrendingUp size={18} />,
    title: "Higher Retention & Reduced Churn",
    desc: "Identify and re‑engage at‑risk members early, reducing churn and preserving your customer base."
  },
  {
    icon: <Target size={18} />,
    title: "Optimized Reward Spend",
    desc: "Allocate rewards where they have the greatest impact on member behavior and business profitability."
  },
  {
    icon: <Zap size={18} />,
    title: "Data‑Driven Program Refinement",
    desc: "Continuously improve your loyalty program based on real‑time performance data and member feedback."
  },
  {
    icon: <CheckCircle size={18} />,
    title: "Competitive Differentiation",
    desc: "Build a loyalty program that truly rewards customers and sets you apart from competitors."
  },
  {
    icon: <Award size={18} />,
    title: "Enhanced Customer Advocacy",
    desc: "Loyal customers become brand advocates, generating word‑of‑mouth and positive reviews that attract new customers."
  },
];

const CustomerLoyaltyAnalyticsPage = () => {
  return (
    <PageLayout>
    <SEO
      title="Customer Loyalty Analytics | Scape Data Solutions"
      description="AI-powered analytics that optimize your loyalty program, predict churn, and maximize customer lifetime value."
      path="/services/customer-loyalty-analytics"
      schema={buildServiceSchema({
        name: "Customer Loyalty Analytics",
        description: "AI-powered analytics that optimize your loyalty program, predict churn, and maximize customer lifetime value.",
        path: "/services/customer-loyalty-analytics",
      })}
    />

      <section className={styles.heroSection}>
        <div className={styles.heroOverlay} />
        <div className={styles.container}>
          <motion.div className={styles.heroContent} initial="hidden" animate="visible" variants={fadeUp}>
            <motion.div className={styles.heroBadge} variants={fadeUp}>
              <Heart size={14} /> <span>Customer Loyalty Analytics</span>
            </motion.div>
            <motion.h1 className={styles.heroTitle} variants={fadeUp}>
              Build Unbreakable <span className={styles.highlight}>Customer Loyalty</span>
            </motion.h1>
            <motion.p className={styles.heroSub} variants={fadeUp}>
              AI-powered analytics that optimizes your loyalty program, predicts churn, and maximizes
              customer lifetime value. Turn casual customers into dedicated brand advocates.
            </motion.p>
            <motion.div className={styles.heroCta} variants={fadeUp}>
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <Link to="/contact" className={styles.heroBtn}>
                  Build Loyalty <ArrowRight size={16} />
                </Link>
              </motion.div>
              <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
                <a href="#how-it-works" className={styles.heroBtnSecondary}>
                  See How It Works <Eye size={15} />
                </a>
              </motion.div>
            </motion.div>
            <motion.div className={styles.heroStats} variants={fadeUp}>
              <div className={styles.statItem}>
                <span className={styles.statValue}>20-30%</span>
                <span className={styles.statLabel}>CLV Increase</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statValue}>25%</span>
                <span className={styles.statLabel}>Churn Reduction</span>
              </div>
              <div className={styles.statItem}>
                <span className={styles.statValue}>15%</span>
                <span className={styles.statLabel}>Program ROI</span>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </section>

      <section className={styles.problemSection}>
        <div className={styles.container}>
          <motion.div
            className={styles.problemContent}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            <span className={styles.problemLabel}>The Challenge</span>
            <h2>Loyalty Programs are <span className={styles.highlight}>Underperforming</span></h2>
            <div className={styles.problemGrid}>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>60%</span>
                <p>Of loyalty program members are inactive, yet they continue to receive rewards and communications, wasting marketing spend.</p>
              </div>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>40%</span>
                <p>Of retailers lack the analytics to measure the true ROI of their loyalty program, unable to justify investment.</p>
              </div>
              <div className={styles.problemStat}>
                <span className={styles.problemNumber}>$100B</span>
                <p>Estimated value of unredeemed loyalty points — a significant liability that could be converted into revenue.</p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <section className={styles.overviewSection}>
        <div className={styles.container}>
          <div className={styles.overviewGrid}>
            <motion.div
              className={styles.overviewText}
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: false, amount: 0.2 }}
              transition={{ duration: 0.6 }}
            >
              <h2>
                Turn Loyalty into a <span className={styles.highlight}>Profit Engine</span>
              </h2>
              <p>
                A well‑designed loyalty program can be a powerful driver of customer retention, repeat
                purchases, and brand advocacy. Yet many programs are underperforming — bloated with
                inactive members, offering irrelevant rewards, and failing to deliver measurable ROI.
              </p>
              <p>
                Our Customer Loyalty Analytics service provides a comprehensive view of your loyalty
                program's performance. We analyze member engagement, redemption patterns, incremental
                spend, and churn risk. We identify which rewards drive the highest loyalty and which
                segments are most valuable.
              </p>
              <p>
                We use machine learning to predict member churn and recommend targeted interventions —
                personalized offers, tier upgrades, or re‑engagement campaigns. We help you optimize
                reward structures to maximize member satisfaction while protecting margins.
              </p>
              <p>
                Ultimately, we help you build a loyalty program that strengthens customer relationships,
                increases lifetime value, and drives sustainable revenue growth.
              </p>
            </motion.div>
            <motion.div
              className={styles.overviewVisual}
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: false, amount: 0.2 }}
              transition={{ duration: 0.6 }}
            >
              <div className={styles.visualPlaceholder}>
                <Heart size={48} />
                <span>Loyalty Analytics</span>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      <section className={styles.howSection} id="how-it-works">
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            Our Approach
          </motion.h2>
          <div className={styles.howGrid}>
            {steps.map((step, index) => (
              <motion.div
                key={index}
                className={styles.howCard}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false, amount: 0.15 }}
                variants={cardVariants}
                whileHover={{ y: -4, boxShadow: "0 8px 24px rgba(0,0,0,0.05)" }}
              >
                <div className={styles.howIcon}>{step.icon}</div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.deliverablesSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            What We Deliver
          </motion.h2>
          <div className={styles.deliverablesGrid}>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Loyalty Program Health Dashboard</h4>
                <p>Real‑time visibility into active members, redemption rates, program ROI, and engagement trends.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Member Segmentation & Tier Analysis</h4>
                <p>Detailed segmentation of members by tier, activity, and value, with recommendations for targeted engagement.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Churn Prediction & Retention Strategy</h4>
                <p>Identification of at‑risk members with personalized re‑engagement plans to prevent churn.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Reward Optimization & Personalization Plan</h4>
                <p>Recommendations for reward types, levels, and targeting to maximize member satisfaction and program ROI.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Incremental Revenue & ROI Attribution</h4>
                <p>Quantified measurement of program impact on revenue and profitability, with clear ROI calculation.</p>
              </div>
            </div>
            <div className={styles.deliverableItem}>
              <CheckCircle size={20} className={styles.deliverableIcon} />
              <div>
                <h4>Continuous Monitoring & Improvement Dashboard</h4>
                <p>Automated alerts and performance tracking to ensure ongoing program optimization.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className={styles.featuresSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            Core Capabilities
          </motion.h2>
          <div className={styles.featuresGrid}>
            {features.map((feature, index) => (
              <motion.div
                key={index}
                className={styles.featureCard}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: false, amount: 0.15 }}
                variants={cardVariants}
                whileHover={{ y: -4, boxShadow: "0 8px 24px rgba(0,0,0,0.05)" }}
              >
                <div className={styles.featureIcon}>{feature.icon}</div>
                <h3>{feature.title}</h3>
                <p>{feature.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.benefitsSection}>
        <div className={styles.container}>
          <motion.h2
            className={styles.sectionTitle}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.5 }}
          >
            Why Choose Us?
          </motion.h2>
          <div className={styles.benefitsGrid}>
            {benefits.map((benefit, index) => (
              <motion.div
                key={index}
                className={styles.benefitCard}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: false, amount: 0.15 }}
                transition={{ duration: 0.4, delay: index * 0.06 }}
                whileHover={{ x: 4 }}
              >
                <div className={styles.benefitIcon}>{benefit.icon}</div>
                <div>
                  <h3>{benefit.title}</h3>
                  <p>{benefit.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      <section className={styles.ctaSection}>
        <div className={styles.container}>
          <motion.div
            className={styles.ctaContent}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.2 }}
            transition={{ duration: 0.6 }}
          >
            <h2>Ready to Build Unshakeable Customer Loyalty?</h2>
            <p>
              Let's analyze your loyalty program data to unlock deeper customer relationships,
              reduce churn, and maximize lifetime value. You'll turn loyal customers into your
              most powerful growth engine.
            </p>
            <motion.div whileHover={{ scale: 1.04 }} whileTap={{ scale: 0.96 }}>
              <Link to="/contact" className={styles.ctaBtn}>
                Get Started <ArrowRight size={18} />
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>
    </PageLayout>
  );
};

export default CustomerLoyaltyAnalyticsPage;
